import { URL } from "@/config/base"

export default {
    searchNotificationRecords: URL.API_URL + '/notification/record/search',
    readNotificationRecord: URL.API_URL + '/notification/record/read',
    deleteNotificationRecords: URL.API_URL + '/notification/record/delete',
    unReadNotificationRecord: URL.API_URL + '/notification/record/unread',
    readAllNotificationRecords: URL.API_URL + '/notification/record/read-all',
    getNotificationRecordDetail: URL.API_URL + '/notification/record/detail',
    getNotificationSourceDetail: URL.API_URL + '/notification/source/detail',
    getMineNotificationSources: URL.API_URL + '/notification/source/mine',
    addNotificationSource: URL.API_URL + '/notification/source/add',
    updateNotificationSource: URL.API_URL + '/notification/source/update',
    deleteNotificationSource: URL.API_URL + '/notification/source/delete',
    getNotificationTargetDetail: URL.API_URL + '/notification/target/detail',
    getMineNotificationTargets: URL.API_URL + '/notification/target/mine',
    addNotificationTarget: URL.API_URL + '/notification/target/add',
    updateNotificationTarget: URL.API_URL + '/notification/target/update',
    deleteNotificationTarget: URL.API_URL + '/notification/target/delete',
    getMineNotificationTask: URL.API_URL + '/notification/task/mine',
    addNotificationTask: URL.API_URL + '/notification/task/add',
    updateNotificationTask: URL.API_URL + '/notification/task/update',
    deleteNotificationTask: URL.API_URL + '/notification/task/delete',
    getNotificationTaskDetail: URL.API_URL + '/notification/task/detail',
    getNotificationTemplate: URL.API_URL + '/notification/template/all',
} 